# Generated by Django 4.2.5 on 2023-09-23 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tripmgmt', '0007_remove_trip_creator_alter_trip_organizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses_paid', to='tripmgmt.participant')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripmgmt.trip')),
            ],
        ),
    ]
