# Generated by Django 4.2.5 on 2023-09-11 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tripmgmt', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
