# Generated by Django 4.2.5 on 2023-09-11 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tripmgmt', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trip',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
