# Generated by Django 4.2.5 on 2023-09-11 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tripmgmt', '0006_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='creator',
        ),
        migrations.AlterField(
            model_name='trip',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripmgmt.participant'),
        ),
    ]
