# Generated by Django 4.2.5 on 2023-09-14 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tripmgmt', '0007_remove_trip_creator_alter_trip_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='participants',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
