# Generated by Django 4.2.5 on 2023-09-15 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tripmgmt', '0009_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tripmgmt.participant'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='trips', to='tripmgmt.participant'),
        ),
    ]
