# Generated by Django 4.2.5 on 2023-09-28 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tripmgmt', '0012_chatroom_message_chatroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='sender_id',
        ),
    ]
