# Generated by Django 4.2.5 on 2023-09-28 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tripmgmt', '0013_rename_sender_message_sender_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender_id',
            new_name='sender',
        ),
    ]
